liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
    context-path: /modulo
    compression:
        enabled: true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - text/css
            - text/javascript
            - application/javascript
    #port: 8443
    #ssl:
    #    key-store: keystore.jks
    #    key-alias: tomcat
    #    key-store-password: tomcatmvfor
    #tomcat:
    #    compression: 4096
    #    compressableMimeTypes: application/json,application/xml
spring:
    application:
        name: modulo
    datasource:
        #jndi-name: java:jboss/datasources/bootdemo
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.254.17:1521:dev4
        #username: dbamvfor
        #password: dbamvfor
        username: acessodisp
        password: a123
        initialize: false
        initial-size: 1
        max-active: 3
        min-idle: 1
        max-idle: 3
        max-wait: 15000
    data:
        jpa:
            repositories: 
                enabled: true
    jackson:
        locale: pt_BR
        time-zone: America/Sao_Paulo
    jpa:
        database: oracle
        database-platform: org.hibernate.dialect.Oracle10gDialect
        show-sql: true
        open-in-view: true
    mail:
        host: localhost
        port: 25
#        protocol: smtp
#        smtp:
#            auth: false
#            starttls.enable: false
#        from: me@localhost
#        username:
#        password:
    messages:
        basename: messages/messages
        encoding: UTF-8
        cache-seconds: -1
banner:
    location: classpath:/config/banner/banner.txt