package br.com.mv.modulo.exception;

public class MedicamentoException extends Exception {

    /**
	 * Generated By IDE
	 */
	private static final long serialVersionUID = -5443176833858427729L;
	
	public MedicamentoException()
    {
        super();
    }
    public MedicamentoException(String msg)
    {
        super(msg);
    }
}
